### ISSUE TITLE
sekutitech

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#106]
sekutitech created by palau371@gmail.com on 2018-01-30 08:03:33

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>ng ngera a belkul?</p>

**Comment by johnbent** [comment]
toninewton54@yahoo.com replied, <br><br>sekutitech-pushy or crowding you in. Â From oltitech

    On Wednesday, January 31, 2018 12:04 AM, Aleksandr Kuznetsov (Debugle) <notifications@debugle.com> wrote:


  Emails/html
|
|  --- Write ABOVE THIS LINE to reply ---
Aleksandr Kuznetsov posted a new comment on sekutitech :
 ng ngera a belkul? View this on DebugleStop receiving email notifications about this item.  |

  |

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>ke kmal mesaul, ms. Antonia!</p><p>can anybody add some information about this word? or is it full now?</p>

**Comment by s-o-u-a-n-g** [comment]
Ea sekutitech! Bom sesei e ng kmal mekeald. 

Oh crowder! Move over because it’s very hot. 

Root: titech which means wedge or to put something snugly between something. A great example is putting an object under a table leg to keep it from teetering. 

Titech is also used on Keiukl to mean a small snack to tide you over. Oh Desbedall we say Olengel.  

souang
