### ISSUE TITLE
Example Usage of Chetul

### ISSUE THREAD

**Issue by JimGeselbracht** [tekinged/missing#18]
Chetul (n.poss.3s) can either be from chat (smoke, steam) or chut (decay, cancer).  The example sentence "Ng ua ngara a chetul a blim?" shows up as an example usage for both "chat" and "chut," but it really only should be an example of a usage for the latter.  Is there a way to distinguish between two very different meanings of the same word?  I've noticed this for other words with similar multiple meanings and it may require a major data architecture change to accommodate.  Just wondering if it is possible.

BTW, I find the root concept behind mechut (as things get old, they accumulate decay) as fascinating, especially as I get older. :-)

**Comment by johnbent** [comment]
Hey @JimGeselbracht , this is tough. Right now the way that we pull example sentences is purely by searching for strings. Each word does have an ID (e.g. chetul from chat is 3529 and chetul from chut is 22032) but it would be super hard to change things to use those IDs. We would have to go through every single sentence and add the ID for each word in the sentence:

"Ng ua ngara a chetul a blim? -> you would have to go through and add each word's ID. 

Hmm, perhaps we could do the following:

1. Automatically get a list of all homonyms
2. Automatically get a list of all sentences using homonyms
3. Manually augment the metadata for each sentence to specify which of the homonyms is used

Still a ton of work.

I'm going to close this issue here and recreate it in the repository where we (are supposed) to keep the code. This repo is for changes to the database and that one is for changes to the code.

**Comment by johnbent** [comment]
@JimGeselbracht , I'm closing this here and tracking it instead here:
https://github.com/tekinged/tekinged.com/issues/1
