### ISSUE TITLE
medil

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#334]
medil created by jimgeselbracht@yahoo.com on 2021-06-07 16:51:29

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br>The song Stongoros contains the phrase "Di mo choitii medil chelechang e ketmeklii."  When I asked Yoichi Rengiil about the function of the word "medil" in that phrase, he said that it modifies "chelechang" to turn it into "right now" or "at this very moment."  This is the only usage of that word I have found in the song lyrics.  Does anyone else have an opinion on its meaning or derivation?

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br>(Mea di el) medil chelechang.

Medil uaisei

Medil ungil

(The way it is spelled and the way it sounds are different).
Mea di el becomes medil.

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br>Thanks Mar, that makes sense

Sent from Yahoo Mail on Android

**Comment by johnbent** [comment]
jlukesemiwo@gmail.com replied, <br><br>I guess it's an emphasis on more than just time or occurrence of something,
as in this song. I Other use examples:

"Erei e ke mechesang medil ngak a mong."
Since you're busy, I'll go by myself.
Here it comes before "ngak" (me/myself) thereby making it "by myself" or
alone...the point being, no other person(s).

"Ng dikea time medil uaisei em nguu el mong."
There's no time so bring it as is./There's no time so leave it as is and
bring it.
Here it comes before "uaisei" and "uaisei" in this context refers to the
state of something. The "medil" added before "uaisei" puts emphasis on the
current state of whatever this item is...telling the person to not do
anything more.

"Kele becherei a blai medil milkolk."
Don't leave the house dark.

I'm trying to find a pattern that can be explained to make its meaning
clearer... I haven't drank enough coffee though...

:)

**Comment by Gnalu** [comment]
Ka becherei medil uaisei!- Leave it be or as is!
 Mokemetii medil tebull. :-)- leave her be in her poutiness. 

Medim kiei e Ulang!!!-Stay then Ulang!!!

Medil kau kung.-You're on your own.

**Comment by smith-371** [comment]
Me di mkiei e Ulang?!
Me di lekau kung.

isn't it?

**Comment by johnbent** [comment]
Thanks. This seems to be another contraction. Which is what Ulang said at the beginning. :)

Mea di el becomes medil.

Thanks @smith-371 and @Gnalu for your persistence in getting this one done. Closing it now.

**Comment by ChrisPerrette** [comment]
I wonder if this might be better spelled as <i><b>me di l</b>chelechang</i>, giving it a construction similar to <i>el kirel me...</i>.

An example from Johanes 19:22 (as I understand its proper orthography) is, "Beche aike el bla kluches <b>me di l</b>ellechukl." ("Let what I have written be, that it may be continually what is written." / "Let what I have written be the writing.")

So "Di mo choitii medil chelechang e ketmeklii." would become "Di mo choitii me di lechelechang e ketmeklii."

**Comment by smith-371** [comment]
> I wonder if this might be better spelled as me di lechelechang, giving it a construction similar to el kirel me....
> 
> An example from Johanes 19:22 (as I understand its proper orthography) is, "Beche aike el bla kluches me di lellechukl." ("Let what I have written be, that it may be continually what is written." / "Let what I have written be the writing.")
> 
> So "Di mo choitii medil chelechang e ketmeklii." would become "Di mo choitii me di lechelechang e ketmeklii."

yes, it looks more correct without A after ME, not ME A DI LE=, but ME DI LE=

**Comment by JimGeselbracht** [comment]
My 2 cents.  I think it is "me di el chelechang", where the word "el" connects "di" to its modifier "chelechang."  Literal translation:  and so [it is] just [which is] now.  The "lechelechang" doesn't make sense to me since you don't have a hypothetical pronoun (or pronoun prefix) on a noun (, which chelechang is).
Me di el uai sei = medil uai sei = and so [it is] just [which is] like that.
    On Tuesday, October 18, 2022 at 03:46:17 PM PDT, smith-371 ***@***.***> wrote:  
 
 



I wonder if this might be better spelled as me di lechelechang, giving it a construction similar to el kirel me....

An example from Johanes 19:22 (as I understand its proper orthography) is, "Beche aike el bla kluches me di lellechukl." ("Let what I have written be, that it may be continually what is written." / "Let what I have written be the writing.")

So "Di mo choitii medil chelechang e ketmeklii." would become "Di mo choitii me di lechelechang e ketmeklii."


yes, it looks more correct without A after ME, not ME A DI LE=, but ME DI LE=

**Comment by smith-371** [comment]
Jim, this would be reasonable, but the Ulang's example reveals no linker particle, but hypothetical pronouns in that position:

Me di mkiei e Ulang!!!-Stay then Ulang!!!

**Comment by ChrisPerrette** [comment]
If that is the case, why does <i>di</i> now require an <i>el</i> when it usually acts as a qualifier/modifier? Also, why can the hypothetical prefix not affix to a noun? Josephs allows for it (pp. 172, 173), also with emphatic pronouns, although checking now, he uses <i>l</i>- instead of <i>le</i>-.

**Comment by smith-371** [comment]
> although checking now, he uses l- instead of le-.

I guess, Josephs wrote l- before unstressed vowels and le- before stressed vowels.

**Comment by JimGeselbracht** [comment]
I see the word "di" further clarified using "el" in a number of examples:
e ngii di el  molebedebek (where "ngii di el" is abbreviated "ngidil")
e ngii di el bo likrid
me a tutau a delebechel a medengelii / a di el blechoel / a songem el di dorau er ngii


    On Tuesday, October 18, 2022 at 04:07:46 PM PDT, smith-371 ***@***.***> wrote:  
 
 



although checking now, he uses l- instead of le-.


I guess, Josephs wrote l- before unstressed vowels and le- before stressed vowels.

**Comment by johnbent** [comment]
Looks like we can mostly close this one except I'm realizing we don't have l- and le- in our affix list:

https://tekinged.com/show_words.php?lookup=affix

**Comment by smith-371** [comment]
NGII DI EL means 'any'

Thessalonika 2:17:
me di bo blechoel el meruul a ungil e molekoi a ungil tekoi.

BO is surely hypothetical form of MO used after DI here.

**Comment by ChrisPerrette** [comment]
> Looks like we can mostly close this one except I'm realizing we don't have l- and le- in our affix list:
> 
> https://tekinged.com/show_words.php?lookup=affix

Agreed.

**Comment by Lukes-Imeyuns** [comment]
This two letter word "di" is so...versatile...?

Me di el chelechang e morael.

Me di el uaisei em nguu el mong.

Ng di ungil.

Ngii di lak el bol meioud.

E ng di ngak a merur.

Ng di ngak el tang.

Te di liluk.

This language is complex! Lol

**Comment by johnbent** [comment]
Closing this as this is just a contraction. Added the l- and le- prefix in new issue #358
