### ISSUE TITLE
MEIREI

### ISSUE THREAD

**Issue by ChrisPerrette** [tekinged/missing#369]
"Ng diak a lmuut el ngodech el meirei el mo ua klisichel me a rechedel tiang."

Does anyone know what <i>meirei</i> means? I have seen it a few times used for "commandments," but it is not in the tekinged database, so I don't know if there are any other meanings.

**Comment by smith-371** [comment]
this word is from Japanese: https://www.nihongomaster.com/japanese/dictionary/word/51236/meirei-命令-めいれい

**Comment by ChrisPerrette** [comment]
Is it ever used by Palauans? Or is it strictly a borrowed word?

**Comment by johnbent** [comment]
Good question. It is definitely borrowed. So, was it only borrowed by BIBLIA or do Palauans use MEIREI any other time?

**Comment by smith-371** [comment]
we have some examples in the texts: https://tekinged.com/misc/alltext.php

**Comment by johnbent** [comment]
Shows up 3 times and all are from Daniel Ngirairikl's translation of 'Chisel a Iungs er a Belau':

- Ng diak a lmuut el ngodech el _**meirei**_ el mo ua klisichel me a rechedel tiang.
- Ngii el chad a mera el uleba ururt er a mekemad, e ng di oderuchel me a _**meirei**_ a mla er a king el me er ngii a lsekum te dmak.
- Se el lotobed a _**meirei**_ er ngii el mo er a rechedal e ng meringel e ng di rokui el di morenges.

So, Daniel Ngirairikl and Biblia. And Masaharu was an editor of CHISEL. So that's good enough validation for me. Now we just need an autoparse.

**Comment by ChrisPerrette** [comment]
> Se el lotobed a meirei er ngii el mo er a rechedal e ng meringel e ng di rokui el di morenges.

Can someone translate this for me? I would like to use it as an example in the autoparse.

**Comment by Lukes-Imeyuns** [comment]
I use the word and have heard it used by many.

That example sentence: Se el lotobed a meirei er ngii el mo er a rechedal
eng meringel e ng di rokui el di morenges.

What is the context? Rechedal as in relatives? Staff in lower positions and
a supervisor? Group members and leader?

1) When she gives commands to her relatives, they are onerous but are all
obeyed. (literal and verbatim)

2) Although the directives she issued to staff were difficult, they
complied with each of them.

**Comment by johnbent** [comment]
Lukes, it comes from https://tekinged.com/misc/pdf.php?file=captain_wilson_v2 (CHISEL A IUNGS ER A BELAU):
![image](https://user-images.githubusercontent.com/2047294/197315236-8292077d-14da-4455-a949-e93587699013.png)

Charl just translated it also and got something similar but different:
It's hard for her to deliver his commands to her co-workers, but when she does, all her commands are heard.

These are different. One puts the difficulty in the issuing of the commands whereas the other puts it in the commands themselves. Also, one says that the commands are heard but the other goes further and says that the commands were fulfilled.

Maybe it's just not a great sentence. If there is so much difficulty translating it, I believe it should not be an example sentence. I think the examples should reflect the way that Palauans naturally talk. Sometimes it seems like some of the Palauan books (BIBLIA, CHISEL, CHARLOTTE) use weird language that doesn't sound natural to native speakers. 

@ChrisPerrette , CHISEL had three sentences with this word. Maybe the other two are more easily and less ambiguously translated. 

The good news is that the definition is getting pretty clear: orders, commandments, directives, etc.

**Comment by ChrisPerrette** [comment]
Ng diak a lmuut el ngodech el meirei el mo ua klisichel me a rechedel tiang.

How about this one.

Something like, No other decree moves with such power and speed as this.

**Comment by Gnalu** [comment]
meirei-Japanese borrowed, for order/directive/mandate.

**Comment by Lukes-Imeyuns** [comment]
"Se el lotobed a meirei er ngii el mo er a rechedal e ng meringel e ng di
rokui el di morenges."


Charl just translated it also and got something similar but different:
It's hard for her to deliver his commands to her co-workers, but when she
does, all her commands are heard.
This makes it sound like there is another person involved.

These are different. One puts the difficulty in the issuing of the commands
whereas the other puts it in the commands themselves. Also, one says that
the commands are heard but the other goes further and says that the
commands were fulfilled.

The last part of the sentence "meringel e ng di rokui el morenges" makes me
believe that it is the demands or directives that are hard or difficult or
onerous...not easy, rather than *the giving commands itself*. If it was
hard for the person to give commands then it would be something like "Ng
meringel er ngii oltobed a meirei e ng di sel lotobed eng rokui el
morenges." The preceding sentences in that excerpt speak to how great this
person is, so much so that even when his commands are not easy, his people
would still obey, with "blakerreng" and showing their "beltkil a rengrir."

"Morenges" is literally translated as heard but depending on the context,
can also mean something was obeyed, followed, adhered to, etc, as in this
example sentence. His people do not just hear or listen, they take
actions...

Maybe it's just not a great sentence. If there is so much difficulty
translating it, I believe it should not be an example sentence. I think the
examples should reflect the way that Palauans naturally talk. Sometimes it
seems like some of the Palauan books (BIBLIA, CHISEL, CHARLOTTE) use weird
language that doesn't sound natural to native speakers.

I agree! I spent so much time thinking about this sentence and translating
and trying to explain, and at the end I just sent those two translations...
I was going to suggest that we find a different one but could not bring
myself to do it. 🙈

New example sentence:

Ng diak a lmuut el ngodech el meirei el mo ua klisichel me a rechedel tiang.
There is no other decree that moves so powerfully and so quickly as this.

Including "lmuut el.." and "el mo ua" makes me think this is referring to
any future decrees: No other decree will move so powerfully and so quickly
as this.

Simpler one: Ng dik a meirei el ua klisichel ma rechedel tiang. = There is
no other decree that is as powerful and moved as quickly as this one.

Lukes


Se el lotobed a meirei er ngii el mo er a rechedal e ng meringel e ng di

**Comment by ChrisPerrette** [comment]
What is the autoparse code for synonyms? It says l for See Also, but it seems that is for etymologically-related words.

Okay, I just saw the thing about synonyms. Is there an unusual way it has to be done?

**Comment by ChrisPerrette** [comment]
AUTOPARSE
w -o J -b meirei meirei n. command; order; mandate; decree; commandment.
e Ng diak a ngodech el meirei el ua klisichel me a rechedel tiang. --There is no other decree so powerful and fast moving as this.
e A lsekum ng ngar er ngii a chad el omdasu el kmo ng profet me a lechub e ng ngar er a klereng e bo lodenge aike el tekoi el kuluches el eko er kemiu el kmo ng meirei er a Rubak. --If anyone thinks he is a prophet or spiritual, let him acknowledge that the things I write to you are the commandments of the Lord.
s meirei bul llach

**Comment by johnbent** [comment]
Correct. I have not yet implemented synonyms nor antonyms in AUTOPARSE. You
are right about 'l' being intended for etymologically-related words.

If you want to put synonyms or antonyms into an AUTOPARSE, please go ahead
and so so. Use 's' for synonyms (e.g. 's oungelakel feik) and 'a' for
antonyms (e.g. 'a make kats').

When we have an AUTOPARSE with those features in it, I'll go ahead and
implement the support for it.

**Comment by ChrisPerrette** [comment]
Can you check if I did that correctly?

**Comment by johnbent** [comment]
Thanks for the autoparse @ChrisPerrette . Three small comments:
1. I don't understand why there are commas between commands, orders, mandate, decree but then a semi-colon between decree and commandment. Also, I don't understand why command, mandate, decree, and commandment are singular but order is plural. I would suggest to make them all singular and replace all commas with semi-colons.
2. There should not be a word 'Eng' in the english translation of your first example sentence.
3. Go ahead and add synonyms using 's meirei bul' and add more words like 's meirei bul llach' if you want. However, if you do multiple words, all will become synonyms of each other. If you want meirei to be a synonym of bul and a synonym of llach but you don't want llach and bul to be synonyms, then do two lines: 's meirei bul' and 's meirei llach'.

@smith-371 , can you please check the example sentences for spelling and grammar. I'm not sure about the 'e ng ngar er a klereng' for example. If it is good, can you give a thumbs-up to the autoparse comment please. 

@Gnalu , @Lukes-Imeyuns , and Souang, can you please check the example sentences and give a thumbs-up to the autoparse comment if the sentences and translations look good to you?

**Comment by johnbent** [comment]
> Can you check if I did that correctly?

**Comment by ChrisPerrette** [comment]
Is there a way to reference a specific ID in the synonyms? BUL, for example, has a few homonyms.

**Comment by johnbent** [comment]
> Is there a way to reference a specific ID in the synonyms? BUL, for example, has a few homonyms.

Great question. When the autoparse finds homonyms, it asks the user (me) to disambiguate. For example, it looks like this:

	Searching for chur, n., xx
	0: Add to n. laughter; laughing. [chur a dereuakl, ocherechur, rekebil a metemella er a chur. ] [id 4055, root 4055, group size 10]
	1: Add to n. tongue. [chur a ngar er a chelsel a ngor el omeob a tekoi; chural a chad. ] [id 4064, root 4064, group size 13]
	2: Add to n. subsidiary rib of coconut frond (with leaves attached. [chur a churul a dui, temikel. ] [id 4072, root 4072, group size 3]
	N: As a new word
	U: Update existing to link to this group
	S: Do not enter right now
	I: Do not enter now but use this word as the root for the rest of the group.
	Q: Quit
	Which word to use as root: 

So, don't worry about homonyms. The script and I will resolve them correctly.

**Comment by ChrisPerrette** [comment]
Okay, awesome.

**Comment by smith-371** [comment]
we don't have KLERENG in our dictionary. Chris' spelling is very nice)

**Comment by johnbent** [comment]
> we don't have KLERENG in our dictionary. 

Can you please create an Issue for it?

> Chris' spelling is very nice)

Can you please give the comment a thumbs-up?

**Comment by johnbent** [comment]
![40689.1666695754.png](https://tekinged.com//tekinged.com/tmp/screenshots/40689.1666695754.png)

**Comment by johnbent** [comment]
AUTOPARSE successfully AUTOPARSED.
@%s, please check the website (and any screenshots above).
If everything looks good, please close this Issue.

**Comment by johnbent** [comment]
![40689.1666696223.png](https://tekinged.com/tmp/screenshots/40689.1666696223.png)

**Comment by johnbent** [comment]
AUTOPARSE successfully AUTOPARSED.<br>@ChrisPerrette, please check the website (and any screenshots above).<br>If everything looks good, please close this Issue.

**Comment by johnbent** [comment]
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/2047294/197682972-09b3e3ed-df4a-4461-9846-86762cbda9ae.png">

**Comment by johnbent** [comment]
AUTOPARSE successfully AUTOPARSED.<br>@ChrisPerrette, please check the website (and any screenshots above).<br>If everything looks good, please close this Issue.

**Comment by ChrisPerrette** [comment]
Looks good.
