### ISSUE TITLE
Visual Display Bug

### ISSUE THREAD

**Issue by ChrisPerrette** [tekinged/missing#373]
![image](https://user-images.githubusercontent.com/116015127/197317622-c619d355-af60-4e51-8496-900cf01a338d.png)

Anyone else getting these random numbers and CSS glitches?

P.S., Sorry John, I keep pulling you back into the code

**Comment by johnbent** [comment]
LOL. No worries! The biggest problem right now with tekinged is that I haven't set up a test bed. So when I make changes, I just do them on the actual site. So those are some of the debug messages I was temporarily printing in order to make the changes. Thanks for reporting that. Should be off now. Can you refresh please and close this Issue if they are now gone for you?

**Comment by ChrisPerrette** [comment]
All good now.

**Comment by Lukes-Imeyuns** [comment]
Totally unrelated but I noticed the "Damn!" there for "Akii!"

How about just "ouch"?

**Comment by johnbent** [comment]
> Totally unrelated but I noticed the "Damn!" there for "Akii!" How about just "ouch"?

Changed.
