### ISSUE TITLE
FEATURE REQUEST: Links and Tooltips in the Palauan Example Text Page

### ISSUE THREAD

**Issue by ChrisPerrette** [tekinged/missing#390]
Would it be too much to ask for clickable links and tooltips in the Palauan text on the Palauan Example Text page? Hopefully most of the code from the main page would be reusable.

**Comment by johnbent** [comment]
Should be easy. I believe that page is already created by a shared function called something like make_table_page which is also the same function which makes the word lists. I just need to modify that function to identify columns which are pal text (should be easy since database table schemas are mostly consistent) and then pass those columns to the pwords_to_plinks function.

**Comment by johnbent** [comment]
Nice suggestion; thanks!

**Comment by johnbent** [comment]
Hey @ChrisPerrette , I think I did this successfully. Can you check please and close this issue if it looks good to you?

Thanks again for this suggestion. Sorry it took me forever to get to this. Wow, it took me seven months. :(

**Comment by johnbent** [comment]
You might need to flush and refresh your cache. I had to do that to see changes in chrome.

**Comment by ChrisPerrette** [comment]
![image](https://github.com/tekinged/missing/assets/116015127/90ffc84a-c02f-4e75-ac86-a967c7f8661f)
Hey, it seems like it mostly works.
