### ISSUE TITLE
etymology for "Spanish" words from the Americas

### ISSUE THREAD

**Issue by jesseseeem** [tekinged/missing#473]
Hi! Just a random thought while looking at the "Word List: Borrowed Spanish" 
Would it make sense to acknowledge the original language for some of these words? Even if they were probably taught to /overheard by Palauans during interactions with people speaking Spanish, words like Guava, Chocolate, Tapioca, were originally borrowed from the Taíno, Nahuatl, and Tupi, respectively (it's easy to guess the fruits/veggies, since we often borrow indigenous words from where ever they were domesticated... so "Maize" is also from the New World, and is probably Taíno; "Tomato" is probably from the Nahuatl). I guess at some point there'd be a cut-off, like Sanskrit "śarkarā" being the origin of sugar/azúcar—that word could have been part of Spanish as long as Spanish existed, even if it was originally from another language. But for words that would have been borrowed by the Spanish between the late 1400s and the early 1700s, it might make sense to note the original languages?

**Comment by johnbent** [comment]
Yeah, that's a nice idea. We already have this in place for some words. For example, check out
https://tekinged.com/?lookup=kerebou&direction=pe

I'm not super comfortable with "probably from" but if you have confidence that you know the path, we can certainly augment them.

On the other hand, if people really want to study the etymology of Spanish words, they'll be doing it somewhere else. If we list a word as coming from the Spanish, then people can look that up in a Spanish dictionary and presumably find an accurate etymology.

**Comment by jesseseeem** [comment]
Totally fair! I definitely understand it's outside of the scope of the dictionary to trace the full etymological history of every loan word. I guess I was just thinking, as a native English speaker, it's funny (but completely plausible) to see "tomato" listed in the "Borrowed from Japanese" list. It does say [From J fr E?] ] on the definition page, but I thought I'd just say something about the ultimate origin since there might not be a lot of native Nahuatl speakers reading tekinged.com to chime in with "wait a minute, that word's from my language!" 

For what it's worth, here's what the Merriam-Webster online dictionary lists under the "etymology" section for each of these words in English (which have cognates in Spanish, and, in some cases, Japanese), but this is not necessarily the universally-agreed-upon etymology [my notes in brackets]
https://www.merriam-webster.com/dictionary/ 

Bamboo: Malay bambu  [jesse's note: more complicated etymology here: https://en.wiktionary.org/wiki/bamboo ] 
Chocolate: Spanish, from Nahuatl chocolātl, probably an alteration of eastern Nahuatl dialect chikolātl, from chikolli hook (probably used to refer to the beater used to mix chocolate with water) + ātl water, liquid

Curry: Tamil kaṟi (or a cognate word in another Dravidian language) [jesse's note: it's also カレー/ karē in Japanese]
Guava: Spanish guaba, guayaba, perhaps from Taino
Maize: Spanish maíz, from Taino mahiz
Okra: of African origin; akin to Ibo ókùrù okra 
Potato: Spanish batata, from Taino
Tapioca: Portuguese, from Tupi tɨpɨʔóka
Tomato: alteration of earlier tomate, from Spanish, from Nahuatl tomatl

**Comment by johnbent** [comment]
I'm going to close this Issue but thanks for reporting it!

Perhaps the better way to think about tekinged's "borrow" tag is from which period of colonial occupation was the word added. I've always enjoyed that. You can get an idea of when a particular thing was introduced to Palau from the borrow tag. Bicycles and paper were introduced by the Germans and Christianity by the Spanish for example. And I personally find it very cool that dogs apparently came over on the rafts with the original settlers.

**Comment by jesseseeem** [comment]
Well, I defer to you on this. Thanks for the insights! 

Funny you mentioned dogs, because someone told me that the first dog Palauans in the 1700s had seen was from one of the European ships that shipwrecked there, and the dog's name happened to be "Phyllis," so that's where they got "bilis" from... but maybe that's just a folk etymology... or the Palauan guy who told me was just messing with me. Wouldn't be the first time :) 

I had just stumbled upon this article saying that there weren't dogs in Palau at the time of first European contact, but I guess I wouldn't be surprised either way if there were dogs in Palau, since they were definitely in the Philippines, PNG, and lots of other places in Oceania including (according to the article below) Ngulu... 

Anyway, thanks again for all your work on this, and sorry for being annoying! 

https://onlinelibrary.wiley.com/doi/abs/10.1002/arco.5252 
(pdf and supplemental linked in google drive folder below)
https://drive.google.com/drive/folders/1IXR_DOxCHXgQMGZ45g_QKd5ZwclUuyTY?usp=sharing

**Comment by johnbent** [comment]
You are _not_ annoying! We are thrilled to have your participation in our community!

Thanks for sharing that about dogs. I had just been assuming on the basis of BILIS looking like a Palauan native word and not matching any known potential origin languages. It would be great to capture discussions like this better in tekinged but I'm not sure about the best way to do it. 

Please let me know if you have any thoughts. One thing I might be able to do pretty easily would be to enable Disqus discussions on each individual word page like https://tekinged.com/index.php?p=bilis. I'm just a bit reluctant to add to clutter as well as to make promises for how future John will spend his time. :)

**Comment by JimGeselbracht** [comment]
Jesse:  I have heard the same story, and it is backed up by Captain Wilson's account (it was his shipwreck you are referring to).  They had two dogs on the ship -- a spaniel and a newfoundland -- and according to the account, Ibedul's son "Arra Kooker" was quite taken by them (see, e.g., page 51 of the account here: ) https://books.google.com/books?id=i8QRAAAAYAAJ&vq=dog&pg=PA51#v=snippet&q=dog&f=false

The account doesn't say anything about the name "Phyllis" -> bilis, but I have heard the same explanation.  Even if not true, it makes a good story.    On Wednesday, May 8, 2024 at 12:53:12 PM PDT, Jesse Czekanski-Moir ***@***.***> wrote:  
 
 


Well, I defer to you on this. Thanks for the insights!

Funny you mentioned dogs, because someone told me that the first dog Palauans in the 1700s had seen was from one of the European ships that shipwrecked there, and the dog's name happened to be "Phyllis," so that's where they got "bilis" from... but maybe that's just a folk etymology... or the Palauan guy who told me was just messing with me. Wouldn't be the first time :)

I had just stumbled upon this article saying that there weren't dogs in Palau at the time of first European contact, but I guess I wouldn't be surprised either way if there were dogs in Palau, since they were definitely in the Philippines, PNG, and lots of other places in Oceania including (according to the article below) Ngulu...

Anyway, thanks again for all your work on this, and sorry for being annoying!

https://onlinelibrary.wiley.com/doi/abs/10.1002/arco.5252
(pdf and supplemental linked in google drive folder below)
https://drive.google.com/drive/folders/1IXR_DOxCHXgQMGZ45g_QKd5ZwclUuyTY?usp=sharing

**Comment by johnbent** [comment]
The books says it was his first time having seen _that_ dog not necessarily his first time having seen any dog. But, that's also weird because _of course_ it would be his first time seeing that dog.

In any event, I love this discussion so I went ahead and modified BILIS to add:
from E? Possibly named after a dog on Captain Wilson's boat named Phyllis.

**Comment by smith-371** [comment]
John, I'd read an archeological research about Palau, there were some dogs in Palau before Europeans but those dogs were extinguished in some way till the time Europeanse came... so, the problem of the sourceword for BILIS really looks very interesting. I know there is a word ma-bilis in Philippines meaning "fast", but the version with Phyllis dog is also probable, because in Nauruan (another language in Micronesia) dogs are called "robar", because the German governor of Nauru had had the dog calling Robert.

**Comment by smith-371** [comment]
in any case, the problem of absorbtion non-Palauan words by the Palauan language is not straightforward to resolve. sometimes European words could get to Palau not from Spaniards thoroughly, but through Yapese people, or any else neighbor nations.

**Comment by smith-371** [comment]
that's why, as for I guess, we should be attentive indicating the source language of a borrowed word in Palauan. a good example of this kind is ASUFARUTO. it's obvious that it originates from English, but got to Palau through Japanese. which language should be indicated as source one? I guess Japanese, because we can be sure that English L always is R in Japanese.

**Comment by smith-371** [comment]
another problem is DIOKANG. tapioca is South American plant and South American Indigenous word. Historically we know, that Spaniards brought tapioca to Palau. but this way of thinking doesn't explain, how we got DIOKANG from TAPIOCA? I suggest, there were some other intermediate links in this word trip.
