### ISSUE TITLE
Obuokel

### ISSUE THREAD

**Issue by palaulanguage** [tekinged/missing#518]
Oreomel el ukelall a usbechall el kerrekar er ngii 

approved by PLC

**Comment by johnbent** [comment]
Added under omukel as a v.a.s.
https://tekinged.com/index.php?p=omukel
Which is fine but maybe incorrect since omukel already has another v.a.s.
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/a8efcc86-8817-4779-bef0-6e2319e62728">
Let me know if you want this moved to either another word or if it should appear as an independent word. Closing for now but please comment here if you want a change.
