### ISSUE TITLE
Fritada

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#533]
Seems to be missing. How would we define it? Is it just a stew made with organ meat? Typically turtle or pig?

**Comment by JimGeselbracht** [comment]
Someone told me that the word fritada is a redundancy of the English word "free" and the Japanese word "tada", which also means free of charge. It is made from parts that would otherwise be thrown away.

Jim Geselbracht
________________________________
From: John Bent ***@***.***>
Sent: Saturday, October 12, 2024 12:28:39 PM
To: tekinged/missing ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tekinged/missing] Fritada (Issue #533)


Seems to be missing. How would we define it? Is it just a stew made with organ meat? Typically turtle or pig?

**Comment by johnbent** [comment]
That's a cute etymology. But I suspect this site is more accurate which claims it comes from Spanish:

https://www.guampedia.com/fritada-pork-beef-or-venison-blood-stew/#:~:text=Description,with%20onions%2C%20vinegar%20and%20spices.

**Comment by Lukes-Imeyuns** [comment]
Yes, John. I remember hearing somewhere that it came from that word. The
only difference is that with our fritada, it's more than just organs. But
yes, it is cooked in blood.

**Comment by Gnalu** [comment]
I think the most important ingredient is the blood, my son says’ make
bloody food.’
Blood stew.

**Comment by johnbent** [comment]
Added. Closing.

FYI @palaulanguage.2@gmail.com.
